"""Shared input/output utilities for CellExLink."""

from __future__ import annotations

from .bioc import (
    child_text,
    clone_bioc_without_annotations,
    collect_document_text,
    convert_bioc_to_jsonl,
    get_infons,
    iter_bioc_annotations,
    iter_bioc_passages,
    iter_input_files,
    read_bioc_tree,
    remove_infons_by_prefix,
    set_child_text,
    set_infon,
    write_bioc_tree,
    write_predictions_to_bioc,
    write_text_as_bioc,
    write_texts_as_bioc,
)
from .jsonl import (
    atomic_write_jsonl,
    ensure_parent_dir,
    load_json,
    load_jsonl,
    load_passage_records,
    read_jsonl,
    read_passage_records,
    read_tsv,
    write_json,
    write_jsonl,
    write_passage_records,
    write_tsv,
)
from .schemas import (
    BioCAnnotation,
    BioCPassage,
    CellExLinkDocumentResult,
    EntitySpan,
    LinkedEntity,
    PassageRecord,
    PathLike,
    coerce_entity_span,
    coerce_passage_record,
    ensure_no_overlapping_spans,
    find_overlapping_spans,
    spans_overlap,
    to_jsonable,
)

__all__ = [
    "BioCAnnotation",
    "BioCPassage",
    "CellExLinkDocumentResult",
    "EntitySpan",
    "LinkedEntity",
    "PassageRecord",
    "PathLike",
    "atomic_write_jsonl",
    "child_text",
    "clone_bioc_without_annotations",
    "coerce_entity_span",
    "coerce_passage_record",
    "collect_document_text",
    "convert_bioc_to_jsonl",
    "ensure_no_overlapping_spans",
    "ensure_parent_dir",
    "find_overlapping_spans",
    "get_infons",
    "iter_bioc_annotations",
    "iter_bioc_passages",
    "iter_input_files",
    "load_json",
    "load_jsonl",
    "load_passage_records",
    "read_bioc_tree",
    "read_jsonl",
    "read_passage_records",
    "read_tsv",
    "remove_infons_by_prefix",
    "set_child_text",
    "set_infon",
    "spans_overlap",
    "to_jsonable",
    "write_bioc_tree",
    "write_json",
    "write_jsonl",
    "write_passage_records",
    "write_predictions_to_bioc",
    "write_text_as_bioc",
    "write_texts_as_bioc",
    "write_tsv",
]
